version: "3.9"

services:
  feedmewell_bot:
    build:
      context: ./bot_files/
      dockerfile: "Dockerfile-prod"
    container_name: feedmewell_bot
    env_file:
      - .env
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    name: backend
    driver: bridge